AWSTemplateFormatVersion: "2010-09-09"
Description: A sample template
Resources:
  myNetwork:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 10.1.0.0/16
      Tags:
        - Key: "Name"
          Value: "my-vpc-cf2"